/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;

public class App {

    public static void main(String[] args) throws IOException {
        String message = (args.length < 3) ? "Ensure you are providing inputPath outputPath Operation" : "";
        System.out.println(message);
        if (args.length < 3) {
            System.exit(1);
        }

        File inputPath = new File(args[0]);
        File outputPath = new File(args[1]);
        String operationName = args[2];

        BufferedImage originalImage = ImageIO.read(inputPath);
        Bitmap imageBitmap = new Bitmap(originalImage);

        if (operationName.equals("negative")) {
            imageBitmap.negative();
        } else if (operationName.equals("Border")) {
            imageBitmap.addBorder();

        } else if (operationName.equals("flip")) {
            imageBitmap.flip();

        } else {
            System.out.println("Operation is not supported");
            System.exit(1);
        }
        ImageIO.write(imageBitmap.getBufferedImage(), "bmp", outputPath);
    }
}
